import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://porterful.com'

  return [
    {
      url: baseUrl,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'daily',
      priority: 1,
    },
    {
      url: `${baseUrl}/shop`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.9,
    },
    {
      url: `${baseUrl}/music`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.9,
    },
    {
      url: `${baseUrl}/artists`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.9,
    },
    {
      url: `${baseUrl}/artist/od-porter`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/tap`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/radio`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/playlists`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/trending`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/superfan`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/brands`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/about`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/contact`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/faq`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/support`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/signal`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/apply`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/signup`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/signup/superfan`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/terms`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'monthly',
      priority: 0.5,
    },
    {
      url: `${baseUrl}/privacy`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'monthly',
      priority: 0.5,
    },
    {
      url: `${baseUrl}/refund`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'monthly',
      priority: 0.5,
    },
    {
      url: `${baseUrl}/dmca`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'monthly',
      priority: 0.5,
    },
    {
      url: `${baseUrl}/moral-policy`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'monthly',
      priority: 0.5,
    },
    {
      url: `${baseUrl}/press-kit`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'monthly',
      priority: 0.5,
    },
    {
      url: `${baseUrl}/onboarding`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'monthly',
      priority: 0.5,
    },
    {
      url: `${baseUrl}/challenge`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/resources`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/blog`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/ecosystem`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/systems`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/kids-chains`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/proud-to-pay`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.8,
    },
    {
      url: `${baseUrl}/album/ambiguous`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.7,
    },
    {
      url: `${baseUrl}/album/from-feast-to-famine`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.7,
    },
    {
      url: `${baseUrl}/album/god-is-good`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.7,
    },
    {
      url: `${baseUrl}/album/one-day`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.7,
    },
    {
      url: `${baseUrl}/album/streets-thought-i-left`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.7,
    },
    {
      url: `${baseUrl}/album/roxannity`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.7,
    },
    {
      url: `${baseUrl}/album/artgasm`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.7,
    },
    {
      url: `${baseUrl}/album/levi`,
      lastMod: new Date('2026-10-02'),
      changeFreq: 'weekly',
      priority: 0.7,
    },
  ]
}
